// Country translations for common countries
const countryTranslations: Record<string, Record<string, string>> = {
  en: {
    // Keep English names as default
  },
  fr: {
    'United States': 'États-Unis',
    'United Kingdom': 'Royaume-Uni',
    'France': 'France',
    'Germany': 'Allemagne',
    'Spain': 'Espagne',
    'Italy': 'Italie',
    'Canada': 'Canada',
    'Australia': 'Australie',
    'Japan': 'Japon',
    'China': 'Chine',
    'India': 'Inde',
    'Brazil': 'Brésil',
    'Mexico': 'Mexique',
    'Argentina': 'Argentine',
    'Chile': 'Chili',
    'Colombia': 'Colombie',
    'Peru': 'Pérou',
    'Venezuela': 'Venezuela',
    'Ecuador': 'Équateur',
    'Bolivia': 'Bolivie',
    'Paraguay': 'Paraguay',
    'Uruguay': 'Uruguay',
    'Guyana': 'Guyana',
    'Suriname': 'Suriname',
    'French Guiana': 'Guyane française',
    'Netherlands': 'Pays-Bas',
    'Belgium': 'Belgique',
    'Switzerland': 'Suisse',
    'Austria': 'Autriche',
    'Portugal': 'Portugal',
    'Greece': 'Grèce',
    'Poland': 'Pologne',
    'Czech Republic': 'République tchèque',
    'Hungary': 'Hongrie',
    'Romania': 'Roumanie',
    'Bulgaria': 'Bulgarie',
    'Croatia': 'Croatie',
    'Slovenia': 'Slovénie',
    'Slovakia': 'Slovaquie',
    'Lithuania': 'Lituanie',
    'Latvia': 'Lettonie',
    'Estonia': 'Estonie',
    'Finland': 'Finlande',
    'Sweden': 'Suède',
    'Norway': 'Norvège',
    'Denmark': 'Danemark',
    'Iceland': 'Islande',
    'Ireland': 'Irlande',
    'Luxembourg': 'Luxembourg',
    'Malta': 'Malte',
    'Cyprus': 'Chypre',
    'Tunisia': 'Tunisie',
    'Morocco': 'Maroc',
    'Algeria': 'Algérie',
    'Egypt': 'Égypte',
    'Libya': 'Libye',
    'Senegal': 'Sénégal',
    'Mali': 'Mali',
    'Burkina Faso': 'Burkina Faso',
    'Niger': 'Niger',
    'Chad': 'Tchad',
    'Cameroon': 'Cameroun',
    'Central African Republic': 'République centrafricaine',
    'Gabon': 'Gabon',
    'Congo': 'Congo',
    'Democratic Republic of the Congo': 'République démocratique du Congo',
    'Angola': 'Angola',
    'Zambia': 'Zambie',
    'Zimbabwe': 'Zimbabwe',
    'Botswana': 'Botswana',
    'Namibia': 'Namibie',
    'South Africa': 'Afrique du Sud',
    'Lesotho': 'Lesotho',
    'Eswatini': 'Eswatini',
    'Mozambique': 'Mozambique',
    'Madagascar': 'Madagascar',
    'Mauritius': 'Maurice',
    'Seychelles': 'Seychelles',
    'Comoros': 'Comores',
    'Djibouti': 'Djibouti',
    'Somalia': 'Somalie',
    'Ethiopia': 'Éthiopie',
    'Eritrea': 'Érythrée',
    'Sudan': 'Soudan',
    'South Sudan': 'Soudan du Sud',
    'Kenya': 'Kenya',
    'Uganda': 'Ouganda',
    'Rwanda': 'Rwanda',
    'Burundi': 'Burundi',
    'Tanzania': 'Tanzanie',
    'Malawi': 'Malawi',
  },
  ar: {
    'United States': 'الولايات المتحدة',
    'United Kingdom': 'المملكة المتحدة',
    'France': 'فرنسا',
    'Germany': 'ألمانيا',
    'Spain': 'إسبانيا',
    'Italy': 'إيطاليا',
    'Canada': 'كندا',
    'Australia': 'أستراليا',
    'Japan': 'اليابان',
    'China': 'الصين',
    'India': 'الهند',
    'Brazil': 'البرازيل',
    'Mexico': 'المكسيك',
    'Argentina': 'الأرجنتين',
    'Chile': 'تشيلي',
    'Colombia': 'كولومبيا',
    'Peru': 'بيرو',
    'Venezuela': 'فنزويلا',
    'Ecuador': 'الإكوادور',
    'Bolivia': 'بوليفيا',
    'Paraguay': 'باراغواي',
    'Uruguay': 'أوروغواي',
    'Guyana': 'غيانا',
    'Suriname': 'سورينام',
    'French Guiana': 'غيانا الفرنسية',
    'Netherlands': 'هولندا',
    'Belgium': 'بلجيكا',
    'Switzerland': 'سويسرا',
    'Austria': 'النمسا',
    'Portugal': 'البرتغال',
    'Greece': 'اليونان',
    'Poland': 'بولندا',
    'Czech Republic': 'جمهورية التشيك',
    'Hungary': 'المجر',
    'Romania': 'رومانيا',
    'Bulgaria': 'بلغاريا',
    'Croatia': 'كرواتيا',
    'Slovenia': 'سلوفينيا',
    'Slovakia': 'سلوفاكيا',
    'Lithuania': 'ليتوانيا',
    'Latvia': 'لاتفيا',
    'Estonia': 'إستونيا',
    'Finland': 'فنلندا',
    'Sweden': 'السويد',
    'Norway': 'النرويج',
    'Denmark': 'الدنمارك',
    'Iceland': 'آيسلندا',
    'Ireland': 'أيرلندا',
    'Luxembourg': 'لوكسمبورغ',
    'Malta': 'مالطا',
    'Cyprus': 'قبرص',
    'Tunisia': 'تونس',
    'Morocco': 'المغرب',
    'Algeria': 'الجزائر',
    'Egypt': 'مصر',
    'Libya': 'ليبيا',
    'Senegal': 'السنغال',
    'Mali': 'مالي',
    'Burkina Faso': 'بوركينا فاسو',
    'Niger': 'النيجر',
    'Chad': 'تشاد',
    'Cameroon': 'الكاميرون',
    'Central African Republic': 'جمهورية أفريقيا الوسطى',
    'Gabon': 'الغابون',
    'Congo': 'الكونغو',
    'Democratic Republic of the Congo': 'جمهورية الكونغو الديمقراطية',
    'Angola': 'أنغولا',
    'Zambia': 'زامبيا',
    'Zimbabwe': 'زيمبابوي',
    'Botswana': 'بوتسوانا',
    'Namibia': 'ناميبيا',
    'South Africa': 'جنوب أفريقيا',
    'Lesotho': 'ليسوتو',
    'Eswatini': 'إسواتيني',
    'Mozambique': 'موزمبيق',
    'Madagascar': 'مدغشقر',
    'Mauritius': 'موريشيوس',
    'Seychelles': 'سيشل',
    'Comoros': 'جزر القمر',
    'Djibouti': 'جيبوتي',
    'Somalia': 'الصومال',
    'Ethiopia': 'إثيوبيا',
    'Eritrea': 'إريتريا',
    'Sudan': 'السودان',
    'South Sudan': 'جنوب السودان',
    'Kenya': 'كينيا',
    'Uganda': 'أوغندا',
    'Rwanda': 'رواندا',
    'Burundi': 'بوروندي',
    'Tanzania': 'تنزانيا',
    'Malawi': 'ملاوي',
  }
};

// Base countries list
const baseCountries: string[] = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

// Function to get translated countries
export const getCountries = (language: 'en' | 'fr' | 'ar' = 'en'): string[] => {
  const translations = countryTranslations[language];
  
  return baseCountries.map(country => 
    translations[country] || country
  );
};

// Export base countries for backward compatibility
export const countries = getCountries('en');
