'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Header
    'cart': 'Cart',
    'login': 'Login',
    'logout': 'Logout',
    'my_profile': 'My Profile',
    'admin_dashboard': 'Admin Dashboard',
    'loading': 'Loading...',
    
    // Navigation
    'home': 'Home',
    'products': 'Products',
    'categories': 'Categories',
    'about': 'About',
    'contact': 'Contact',
    
    // Product related
    'add_to_cart': 'Add to Cart',
    'remove_from_cart': 'Remove from Cart',
    'price': 'Price',
    'quantity': 'Quantity',
    'total': 'Total',
    'subtotal': 'Subtotal',
    'tax': 'Tax',
    'shipping': 'Shipping',
    'free_shipping': 'Free Shipping',
    
    // Checkout
    'checkout': 'Checkout',
    'order_summary': 'Order Summary',
    'payment_method': 'Payment Method',
    'shipping_address': 'Shipping Address',
    'billing_address': 'Billing Address',
    'place_order': 'Place Order',
    'order_confirmation': 'Order Confirmation',
    
    // Invoice
    'invoice': 'INVOICE',
    'bill_to': 'BILL TO',
    'description': 'DESCRIPTION',
    'qty': 'QTY',
    'thank_you': 'THANK YOU FOR YOUR TRUST',
    'download_pdf': 'Download PDF',
    'close': 'Close',
    
    // Profile
    'profile': 'Profile',
    'edit_profile': 'Edit Profile',
    'change_password': 'Change Password',
    'address': 'Address',
    'user_orders': 'Orders',
    'settings': 'Settings',
    
    // Auth
    'register': 'Register',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'name': 'Name',
    'city': 'City',
    'country': 'Country',
    'zip_code': 'Zip Code',
    'subscribe': 'Subscribe to newsletter',
    'forgot_password': 'Forgot Password?',
    'already_have_account': 'Already have an account?',
    'dont_have_account': "Don't have an account?",
    'sign_up': 'Sign Up',
    'sign_in': 'Sign In',
    
    // Messages
    'welcome': 'Welcome',
    'login_success': 'Login successful!',
    'logout_success': 'Logged out successfully',
    'registration_success': 'Registration successful!',
    'error_occurred': 'An error occurred',
    'network_error': 'Network error, please try again',
    'opening_password_change': 'Opening password change',
    'changing_password': 'Changing password',
    'updating_profile': 'Updating profile...',
    'error_loading_profile': 'Error loading profile',
    'edit_mode_enabled': 'Edit mode enabled',
    'password_change_cancelled': 'Password change cancelled',
    'cancelling_order': 'Cancelling order...',
    'cancelling': 'Cancelling...',
    'order_cancelled_successfully': 'Order cancelled successfully',
    'error_cancelling_order': 'Error cancelling order',
    'profile_updated_successfully': 'Profile updated successfully',
    'error_updating_profile': 'Error updating profile',
    'passwords_do_not_match': 'Passwords do not match',
    'password_must_be_at_least_6_characters': 'Password must be at least 6 characters',
    'password_updated_successfully': 'Password updated successfully',
    'error_changing_password': 'Error changing password',
    'administrator': 'Administrator',
    'client': 'Client',
    'items': 'items',
    'confirm_new_password': 'Confirm New Password',
    
    // Admin
    'dashboard': 'Dashboard',
    'users': 'Users',
    'admin_orders': 'Orders',
    'admin_products': 'Products',
    'statistics': 'Statistics',
    'notifications': 'Notifications',
    
    // Common
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'all': 'All',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'submit': 'Submit',
    'reset': 'Reset',
    'clear': 'Clear',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Information',
    'role': 'Role',
    'actions': 'Actions',
    'no_users_found': 'No users found',
    'get_started_add_user': 'Get started by adding your first user to the system.',
    'manage_products_inventory': 'Manage your products and inventory',
    'product_information': 'Product Information',
    'stock_status': 'Stock Status',
    'track_manage_orders': 'Track and manage customer orders',
    'order_details': 'Order Details',
    'customer': 'Customer',
    'amount': 'Amount',
    'status': 'Status',
    'add_new': 'Add New',
    'user': 'User',
    'product': 'Product',
    'order': 'Order',
    'total_users': 'Total Users',
    'total_products': 'Total Products',
    'total_orders': 'Total Orders',
    'total_revenue': 'Total Revenue',
    'no_notifications': 'No notifications',
    'address_details': 'Address Details',
    'street_address': 'Street Address',
    'admin': 'Admin',
    'stock_quantity': 'Stock Quantity',
    'product_name': 'Product Name',
    'category': 'Category',
    'subcategory': 'Subcategory',
    'product_image': 'Product Image',
    'unknown_user': 'Unknown User',
    'no_email_provided': 'No email provided',
    'unknown': 'Unknown',
    'no_location': 'No location',
    'view_details': 'View Details',
    'edit_user': 'Edit User',
    'delete_user': 'Delete User',
    'out_of_stock': 'Out of Stock',
    'unavailable_for_purchase': 'Unavailable for Purchase',
    'in_stock': 'In Stock',
    'low_stock': 'Low Stock',
    'edit_product': 'Edit Product',
    'delete_product': 'Delete Product',
    'no_products_found': 'No products found',
    'get_started_add_product': 'Get started by adding your first product to the catalog.',
    'unknown_date': 'Unknown date',
    'edit_order': 'Edit Order',
    'delete_order': 'Delete Order',
    'no_orders_found': 'No orders found',
    'get_started_add_order': 'Orders will appear here when customers start placing them.',
    'payment_successful': 'Payment Successful!',
    'payment_success_message': 'Thank you for your purchase. Your payment has been processed successfully. We\'ll send you an email confirmation with your order details shortly.',
    'return_to_home': 'Return to Home',
    'view_order_status': 'View Order Status',
    'payment_error': 'Payment Error',
    'payment_error_message': 'Something went wrong during the payment process. Don\'t worry, no charges have been made to your account.',
    'payment_error_help': 'If you continue to experience issues, please contact our support team or try again with a different payment method.',
    'try_again': 'Try Again',
    'payment_pending': 'Payment Processing',
    'payment_pending_message': 'Your payment is being processed. This may take a few moments. We\'ll notify you by email once the payment is confirmed.',
    'payment_pending_warning': 'Please do not close this page or refresh your browser while we process your payment.',
    'check_order_status': 'Check Order Status',
    'back_to_home': 'Back to Home',
    'payment_session_created': 'Payment session created successfully',
    'failed_to_load_payment_session': 'Failed to load payment session',
    'failed_to_create_payment_session': 'Failed to create payment session',
    'new_address_added': 'New address added successfully',
    'using_profile_address': 'Using profile address',
    'failed_to_create_guest_user': 'Failed to create guest user',
    'failed_to_create_order': 'Failed to create order',
    'order_created_successfully': 'Order created successfully',
    'shopping_cart': 'Shopping Cart',
    'cart_empty': 'Your cart is empty.',
    'continue_shopping': 'Continue Shopping',
    'clear_cart': 'Clear Cart',
    'each': 'each',
    'remove': 'Remove',
    'payment_details': 'Payment Details',
    'loading_payment_system': 'Loading payment system...',
    'payment_failed_try_again': 'Payment failed. Please try again.',
    'proceed_to_checkout': 'Proceed to Checkout',
    'special_offers': 'Special Offers',
    'free_shipping_all_orders': 'Free shipping on all orders',
    'thirty_day_return_policy': '30-day return policy',
    'secure_checkout_guaranteed': 'Secure checkout guaranteed',
    'in_stock_count': 'in stock',
    'added_to_cart': 'added to cart!',
    'active': 'Active',
    'left': 'left',
    'add': 'Add',
    'stock_available': 'Stock available',
    'units': 'units',
    'no_description_available': 'No description available for this product.',
    'not_specified': 'Not specified',
    'add_to_cart_quantity': 'Add to cart',
    'product_added_to_cart': 'Product added to cart!',
    'view_my_cart': 'View my cart',
    'close_modal': 'Close modal',
    'update_your_personal_information': 'Update your personal information',
    'profile_information': 'Profile Information',
    'account_overview': 'Account Overview',
    'account_type': 'Account Type',
    'ADMIN': 'ADMIN',
    'security': 'Security',
    'manage_your_account_security': 'Manage your account security',
    'order_history': 'Order History',
    'show_more_orders': 'Show More Orders',
    'show_less': 'Show Less',
    'more': 'more',
    'show_more': 'Show More',
    'showing': 'Showing',
    'of': 'of',
    'products_count': 'products',
    'try_adjusting_filters': 'Try adjusting your filters',
    'no_address_provided': 'No address provided',
    'use_profile_address': 'Use Profile Address',
    'no_address_on_file': 'No address on file',
    'add_new_address': 'Add New Address',
    'enter_shipping_address': 'Enter Shipping Address',
    'enter_different_shipping_address': 'Enter a different shipping address',
    'please_provide_shipping_address': 'Please provide your shipping address',
    'select_country': 'Select Country',
    'continue': 'Continue',
    'full_name': 'Full Name',
    'select_your_country': 'Select your country',
    'enter_your': 'Enter your',
    'not_provided': 'Not provided',
    'saving': 'Saving...',
    'your_orders_will_appear_here': 'Your orders will appear here when you make purchases',
    'passed_on': 'Passed on',
    'login_to_your_account': 'Log in to your account',
    'create_account_few_steps': 'Create your account in a few steps',
    'logging_in': 'Logging in...',
    'create_account': 'Create an account',
    'your_full_name': 'Your full name',
    'minimum_8_characters': 'Minimum 8 characters',
    'strength': 'Strength',
    'street_address_placeholder': '123 Main Street',
    'your_city': 'Your city',
    'subscribe_newsletter': 'I want to receive special offers and news by email',
    'signing_up': 'Signing up...',
    'postal_code': 'Postal Code',
    'select_a_country': 'Select a country',
    'currency_converter': 'Currency Converter',
    'choose_preferred_currency': 'Choose your preferred currency',
    'euro': 'Euro',
    'dinar': 'Dinar',
    'exchange_rate': 'Exchange Rate',
    'real_time_rate': 'Real-time rate',
    'my_orders': 'My Orders',
    'no_orders_yet': "You haven't placed any orders yet.",
    'pending': 'Pending',
    'processing': 'Processing',
    'shipped': 'Shipped',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled',
    'confirm_delete_order': 'Are you sure you want to delete this order?',
    'order_deleted_successfully': '✅ Order deleted successfully!',
    'error_deleting_order': 'Error deleting order',
    'unknown_error': 'Unknown error',
    'no_orders': 'No orders',
    'secure_your_account': 'Secure your account',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'updating': 'Updating...',
    'update': 'Update',
    'member_since': 'Member since',
    'street': 'Street',
    'view_my_orders': 'View My Orders',
    'order_total': 'order',
    'orders_total': 'orders',
    'electronics_hub': 'Electronics Hub',
    'browse_by_category': 'Browse by category',
    'expand_subcategories': 'Expand subcategories',
    'reset_filters': 'Reset Filters',
    
    // Reviews
    'reviews': 'Reviews',
    'write_review': 'Write a Review',
    'rating': 'Rating',
    'comment': 'Comment',
    'submit_review': 'Submit Review',
    'submitting': 'Submitting...',
    'comment_required': 'Comment is required',
    'rating_required': 'Rating must be between 1 and 5',
    // Payment Method Selector
    'choose_payment_method': 'Choose payment method',
    'select_payment_method_description': 'Select your preferred payment method to continue with your secure transaction',
    'adyen_description': 'Pay securely with international cards and wallets.',
    'paymee_description': 'Pay with local methods and Tunisian banks.',
    // Paymee Payment
    'paymee_payment': 'Paymee Payment',
    'secure_payment_with_paymee': 'Secure payment with Paymee',
    'waiting_for_payment': 'Waiting for Paymee Payment',
    'please_complete_payment_in_new_tab': 'Please complete your payment in the new tab.',
    'polling_attempts': 'Polling attempts',
    'retry_check_payment_status': 'Retry checking payment status',
    'redirecting_to_paymee': 'You will be redirected to Paymee to complete your payment.',
    'proceed_to_paymee': 'Proceed to Paymee',
    'payment_instructions': 'Payment instructions',
    'click_proceed_to_complete_payment': "Click 'Proceed to Paymee' to complete your payment.",
    'payment_page_will_open_new_tab': 'The payment page will open in a new tab.',
    'return_here_after_payment': 'Return here after payment to check your status.',
    'creating_payment': 'Creating payment',
    'pay_with_paymee': 'Pay with Paymee',
    'secure_payment': 'Secure payment',
    'paymee_secure_encryption': 'Paymee uses secure encryption',
    'no_card_details_stored': 'No card details are stored',
    'instant_payment_confirmation': 'Instant payment confirmation',
    'payment_created_successfully': 'Payment created successfully',
    'failed_to_create_payment': 'Failed to create payment',
    'payment_still_pending': 'Payment is still pending',
    'failed_to_check_payment_status': 'Failed to check payment status',
    'back_to_payment_methods': 'Back to payment methods',
    'all_payments_secure': 'All payments are secure.',
    'global_coverage': 'Global Coverage',
    'multiple_currencies': 'Multiple Currencies',
    'instant_processing': 'Instant Processing',
    'local_banking': 'Local Banking',
    'tunisian_dinar': 'Tunisian Dinar',
    'trusted_partner': 'Trusted Partner',

  },
  fr: {
    // Header
    'cart': 'Panier',
    'login': 'Connexion',
    'logout': 'Déconnexion',
    'my_profile': 'Mon Profil',
    'admin_dashboard': 'Tableau de Bord Admin',
    'loading': 'Chargement...',
    
    // Navigation
    'home': 'Accueil',
    'products': 'Produits',
    'categories': 'Catégories',
    'about': 'À Propos',
    'contact': 'Contact',
    
    // Product related
    'add_to_cart': 'Ajouter au Panier',
    'remove_from_cart': 'Retirer du Panier',
    'price': 'Prix',
    'quantity': 'Quantité',
    'total': 'Total',
    'subtotal': 'Sous-total',
    'tax': 'Taxe',
    'shipping': 'Livraison',
    'free_shipping': 'Livraison Gratuite',
    
    // Checkout
    'checkout': 'Commander',
    'order_summary': 'Résumé de la Commande',
    'payment_method': 'Méthode de Paiement',
    'shipping_address': 'Adresse de Livraison',
    'billing_address': 'Adresse de Facturation',
    'place_order': 'Passer la Commande',
    'order_confirmation': 'Confirmation de Commande',
    
    // Invoice
    'invoice': 'FACTURE',
    'bill_to': 'FACTURER À',
    'description': 'DESCRIPTION',
    'qty': 'QTÉ',
    'thank_you': 'MERCI POUR VOTRE CONFIANCE',
    'download_pdf': 'Télécharger PDF',
    'close': 'Fermer',
    
    // Profile
    'profile': 'Profil',
    'edit_profile': 'Modifier le Profil',
    'change_password': 'Changer le Mot de Passe',
    'address': 'Adresse',
    'user_orders': 'Commandes',
    'settings': 'Paramètres',
    
    // Auth
    'register': 'S\'inscrire',
    'email': 'Email',
    'password': 'Mot de Passe',
    'confirm_password': 'Confirmer le Mot de Passe',
    'name': 'Nom',
    'city': 'Ville',
    'country': 'Pays',
    'zip_code': 'Code Postal',
    'subscribe': 'S\'abonner à la newsletter',
    'forgot_password': 'Mot de passe oublié?',
    'already_have_account': 'Vous avez déjà un compte?',
    'dont_have_account': 'Vous n\'avez pas de compte?',
    'sign_up': 'S\'inscrire',
    'sign_in': 'Se Connecter',
    
    // Messages
    'welcome': 'Bienvenue',
    'login_success': 'Connexion réussie!',
    'logout_success': 'Déconnexion réussie',
    'registration_success': 'Inscription réussie!',
    'error_occurred': 'Une erreur s\'est produite',
    'network_error': 'Erreur réseau, veuillez réessayer',
    'opening_password_change': 'Ouverture du changement de mot de passe',
    'changing_password': 'Changement du mot de passe',
    'updating_profile': 'Mise à jour du profil...',
    'error_loading_profile': 'Erreur lors du chargement du profil',
    'edit_mode_enabled': 'Mode édition activé',
    'password_change_cancelled': 'Changement de mot de passe annulé',
    'cancelling_order': 'Annulation de la commande...',
    'cancelling': 'Annulation...',
    'order_cancelled_successfully': 'Commande annulée avec succès',
    'error_cancelling_order': 'Erreur lors de l\'annulation de la commande',
    'profile_updated_successfully': 'Profil mis à jour avec succès',
    'error_updating_profile': 'Erreur lors de la mise à jour du profil',
    'passwords_do_not_match': 'Les mots de passe ne correspondent pas',
    'password_must_be_at_least_6_characters': 'Le mot de passe doit contenir au moins 6 caractères',
    'password_updated_successfully': 'Mot de passe mis à jour avec succès',
    'error_changing_password': 'Erreur lors du changement de mot de passe',
    'administrator': 'Administrateur',
    'client': 'Client',
    'items': 'articles',
    'confirm_new_password': 'Confirmer le nouveau mot de passe',
    
    // Admin
    'dashboard': 'Tableau de Bord',
    'users': 'Utilisateurs',
    'admin_orders': 'Commandes',
    'admin_products': 'Produits',
    'statistics': 'Statistiques',
    'notifications': 'Notifications',
    
    // Common
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'edit': 'Modifier',
    'delete': 'Supprimer',
    'view': 'Voir',
    'search': 'Rechercher',
    'filter': 'Filtrer',
    'sort': 'Trier',
    'all': 'Tout',
    'yes': 'Oui',
    'no': 'Non',
    'ok': 'OK',
    'back': 'Retour',
    'next': 'Suivant',
    'previous': 'Précédent',
    'submit': 'Soumettre',
    'reset': 'Réinitialiser',
    'clear': 'Effacer',
    'error': 'Erreur',
    'success': 'Succès',
    'warning': 'Avertissement',
    'info': 'Information',
    'role': 'Rôle',
    'actions': 'Actions',
    'no_users_found': 'Aucun utilisateur trouvé',
    'get_started_add_user': 'Commencez par ajouter votre premier utilisateur au système.',
    'manage_products_inventory': 'Gérez vos produits et votre inventaire',
    'product_information': 'Informations sur le produit',
    'stock_status': 'Statut du stock',
    'track_manage_orders': 'Suivre et gérer les commandes clients',
    'order_details': 'Détails de la commande',
    'customer': 'Client',
    'amount': 'Montant',
    'status': 'Statut',
    'add_new': 'Ajouter',
    'user': 'Utilisateur',
    'product': 'Produit',
    'order': 'Commande',
    'total_users': 'Total Utilisateurs',
    'total_products': 'Total Produits',
    'total_orders': 'Total Commandes',
    'total_revenue': 'Chiffre d\'Affaire',
    'no_notifications': 'Aucune notification',
    'address_details': 'Détails de l\'adresse',
    'street_address': 'Adresse de rue',
    'admin': 'Administrateur',
    'stock_quantity': 'Quantité en stock',
    'product_name': 'Nom du produit',
    'category': 'Catégorie',
    'subcategory': 'Sous-catégorie',
    'product_image': 'Image du produit',
    'unknown_user': 'Utilisateur inconnu',
    'no_email_provided': 'Aucun email fourni',
    'unknown': 'Inconnu',
    'no_location': 'Aucun emplacement',
    'view_details': 'Voir les détails',
    'edit_user': 'Modifier l\'utilisateur',
    'delete_user': 'Supprimer l\'utilisateur',
    'out_of_stock': 'Rupture de stock',
    'unavailable_for_purchase': 'Indisponible pour l\'achat',
    'in_stock': 'En stock',
    'low_stock': 'Stock faible',
    'edit_product': 'Modifier le produit',
    'delete_product': 'Supprimer le produit',
    'no_products_found': 'Aucun produit trouvé',
    'get_started_add_product': 'Commencez par ajouter votre premier produit au catalogue.',
    'unknown_date': 'Date inconnue',
    'edit_order': 'Modifier la commande',
    'delete_order': 'Supprimer la commande',
    'no_orders_found': 'Aucune commande trouvée',
    'get_started_add_order': 'Les commandes apparaîtront ici lorsque les clients commenceront à les passer.',
    'payment_successful': 'Paiement Réussi !',
    'payment_success_message': 'Merci pour votre achat. Votre paiement a été traité avec succès. Nous vous enverrons un email de confirmation avec les détails de votre commande sous peu.',
    'return_to_home': 'Retour à l\'Accueil',
    'view_order_status': 'Voir le Statut de la Commande',
    'payment_error': 'Erreur de Paiement',
    'payment_error_message': 'Quelque chose s\'est mal passé pendant le processus de paiement. Ne vous inquiétez pas, aucun frais n\'a été débité de votre compte.',
    'payment_error_help': 'Si vous continuez à rencontrer des problèmes, veuillez contacter notre équipe de support ou réessayer avec une méthode de paiement différente.',
    'try_again': 'Réessayer',
    'payment_pending': 'Traitement du Paiement',
    'payment_pending_message': 'Votre paiement est en cours de traitement. Cela peut prendre quelques instants. Nous vous notifierons par email une fois le paiement confirmé.',
    'payment_pending_warning': 'Veuillez ne pas fermer cette page ou actualiser votre navigateur pendant que nous traitons votre paiement.',
    'check_order_status': 'Vérifier le Statut de la Commande',
    'back_to_home': 'Retour à l\'Accueil',
    'payment_session_created': 'Session de paiement créée avec succès',
    'failed_to_load_payment_session': 'Échec du chargement de la session de paiement',
    'failed_to_create_payment_session': 'Échec de la création de la session de paiement',
    'new_address_added': 'Nouvelle adresse ajoutée avec succès',
    'using_profile_address': 'Utilisation de l\'adresse du profil',
    'failed_to_create_guest_user': 'Échec de la création de l\'utilisateur invité',
    'failed_to_create_order': 'Échec de la création de la commande',
    'order_created_successfully': 'Commande créée avec succès',
    'shopping_cart': 'Panier d\'Achat',
    'cart_empty': 'Votre panier est vide.',
    'continue_shopping': 'Continuer les Achats',
    'clear_cart': 'Vider le Panier',
    'each': 'chacun',
    'remove': 'Supprimer',
    'payment_details': 'Détails du Paiement',
    'loading_payment_system': 'Chargement du système de paiement...',
    'payment_failed_try_again': 'Paiement échoué. Veuillez réessayer.',
    'proceed_to_checkout': 'Procéder au Paiement',
    'special_offers': 'Offres Spéciales',
    'free_shipping_all_orders': 'Livraison gratuite sur toutes les commandes',
    'thirty_day_return_policy': 'Politique de retour de 30 jours',
    'secure_checkout_guaranteed': 'Paiement sécurisé garanti',
    'in_stock_count': 'en stock',
    'added_to_cart': 'ajouté au panier !',
    'active': 'Actif',
    'left': 'Disponible',
    'add': 'Ajouter',
    'stock_available': 'Stock disponible',
    'units': 'unités',
    'no_description_available': 'Aucune description disponible pour ce produit.',
    'not_specified': 'Non spécifié',
    'add_to_cart_quantity': 'Ajouter au panier',
    'product_added_to_cart': 'Produit ajouté au panier !',
    'view_my_cart': 'Voir mon panier',
    'close_modal': 'Fermer la modal',
    'profile_information': 'Informations du Profil',
    'account_overview': 'Aperçu du Compte',
    'account_type': 'Type de Compte',
    'ADMIN': 'ADMIN',
    'security': 'Sécurité',
    'manage_your_account_security': 'Gérer la sécurité de votre compte',
    'order_history': 'Historique des Commandes',
    'show_more_orders': 'Afficher Plus de Commandes',
    'show_less': 'Afficher Moins',
    'more': 'de plus',
    'show_more': 'Afficher Plus',
    'showing': 'Affichage',
    'of': 'sur',
    'products_count': 'produits',
    'try_adjusting_filters': 'Essayez d\'ajuster vos filtres',
    'no_address_provided': 'Aucune adresse fournie',
    'use_profile_address': 'Utiliser l\'Adresse du Profil',
    'no_address_on_file': 'Aucune adresse enregistrée',
    'add_new_address': 'Ajouter une Nouvelle Adresse',
    'enter_shipping_address': 'Saisir l\'Adresse de Livraison',
    'enter_different_shipping_address': 'Saisir une adresse de livraison différente',
    'please_provide_shipping_address': 'Veuillez fournir votre adresse de livraison',
    'select_country': 'Sélectionner un Pays',
    'continue': 'Continuer',
    'full_name': 'Nom Complet',
    'select_your_country': 'Sélectionnez votre pays',
    'enter_your': 'Saisissez votre',
    'not_provided': 'Non fourni',
    'saving': 'Enregistrement...',
    'your_orders_will_appear_here': 'Vos commandes apparaîtront ici lorsque vous ferez des achats',
    'passed_on': 'Passée le',
    'login_to_your_account': 'Connectez-vous à votre compte',
    'create_account_few_steps': 'Créez votre compte en quelques étapes',
    'logging_in': 'Connexion en cours...',
    'create_account': 'Créer un compte',
    'your_full_name': 'Votre nom complet',
    'minimum_8_characters': 'Minimum 8 caractères',
    'strength': 'Force',
    'street_address_placeholder': '123 Rue Principale',
    'your_city': 'Votre ville',
    'subscribe_newsletter': 'Je souhaite recevoir des offres spéciales et des nouvelles par email',
    'signing_up': 'Inscription en cours...',
    'postal_code': 'Code Postal',
    'select_a_country': 'Sélectionner un pays',
    'currency_converter': 'Convertisseur de Devises',
    'choose_preferred_currency': 'Choisissez votre devise préférée',
    'euro': 'Euro',
    'dinar': 'Dinar',
    'exchange_rate': 'Taux de Change',
    'real_time_rate': 'Taux en temps réel',
    'my_orders': 'Mes Commandes',
    'no_orders_yet': "Vous n'avez pas encore passé de commande.",
    'pending': 'En attente',
    'processing': 'En cours',
    'shipped': 'Expédié',
    'delivered': 'Livré',
    'cancelled': 'Annulé',
    'confirm_delete_order': 'Êtes-vous sûr de vouloir supprimer cette commande ?',
    'order_deleted_successfully': '✅ Commande supprimée avec succès !',
    'error_deleting_order': 'Erreur lors de la suppression de la commande',
    'unknown_error': 'Erreur inconnue',
    'no_orders': 'Aucune commande',
    'secure_your_account': 'Sécurisez votre compte',
    'current_password': 'Mot de Passe Actuel',
    'new_password': 'Nouveau Mot de Passe',
    'updating': 'Mise à jour...',
    'update': 'Mettre à jour',
    'member_since': 'Мembre depuis',
    'street': 'Rue',
    'view_my_orders': 'Voir Mes Commandes',
    'order_total': 'commande',
    'orders_total': 'commandes',
    'electronics_hub': 'Centre Électronique',
    'browse_by_category': 'Parcourir par catégorie',
    'expand_subcategories': 'Développer les sous-catégories',
    'reset_filters': 'Réinitialiser les Filtres',
    
    // Reviews
    'reviews': 'Avis',
    'write_review': 'Écrire un Avis',
    'rating': 'Note',
    'comment': 'Commentaire',
    'submit_review': 'Soumettre l\'Avis',
    'submitting': 'Soumission...',
    'comment_required': 'Le commentaire est requis',
    'rating_required': 'La note doit être entre 1 et 5',
    'login_to_review': 'Veuillez vous connecter pour écrire un avis',
    'write_review_placeholder': 'Partagez votre expérience avec ce produit...',
    'no_reviews_yet': 'Aucun avis pour le moment. Soyez le premier à évaluer ce produit !',
    'error_submitting_review': 'Erreur lors de la soumission de l\'avis',
    'error_updating_review': 'Erreur lors de la mise à jour de l\'avis',
    'error_deleting_review': 'Erreur lors de la suppression de l\'avis',
    'confirm_delete_review': 'Êtes-vous sûr de vouloir supprimer cet avis ?',
    'rating_1': 'Mauvais',
    'rating_2': 'Moyen',
    'rating_3': 'Bon',
    'rating_4': 'Très Bon',
    'rating_5': 'Excellent',
    // Payment Method Selector
    'choose_payment_method': 'Choisissez le moyen de paiement',
    'select_payment_method_description': 'Sélectionnez votre moyen de paiement préféré pour continuer votre transaction sécurisée',
    'adyen_description': 'Payez en toute sécurité avec des cartes et portefeuilles internationaux.',
    'paymee_description': 'Payez avec des méthodes locales et des banques tunisiennes.',
    // Paymee Payment
    'paymee_payment': 'Paiement Paymee',
    'secure_payment_with_paymee': 'Paiement sécurisé avec Paymee',
    'waiting_for_payment': 'En attente du paiement Paymee',
    'please_complete_payment_in_new_tab': 'Veuillez compléter votre paiement dans le nouvel onglet.',
    'polling_attempts': 'Tentatives de vérification',
    'retry_check_payment_status': 'Réessayer la vérification du paiement',
    
    'redirecting_to_paymee': 'Vous serez redirigé vers Paymee pour compléter votre paiement.',
    'proceed_to_paymee': 'Aller sur Paymee',
    'payment_instructions': 'Instructions de paiement',
    'click_proceed_to_complete_payment': "Cliquez sur 'Aller sur Paymee' pour compléter votre paiement.",
    'payment_page_will_open_new_tab': 'La page de paiement s\'ouvrira dans un nouvel onglet.',
    'return_here_after_payment': 'Revenez ici après le paiement pour vérifier votre statut.',

    'creating_payment': 'Création du paiement',
    'pay_with_paymee': 'Payer avec Paymee',
    'secure_payment': 'Paiement sécurisé',
    'paymee_secure_encryption': 'Paymee utilise un chiffrement sécurisé',
    'no_card_details_stored': "Aucune information de carte n'est stockée", 
    'instant_payment_confirmation': 'Confirmation de paiement instantanée',
    'payment_created_successfully': 'Paiement créé avec succès',
    'failed_to_create_payment': 'Échec de la création du paiement',
    'payment_still_pending': 'Le paiement est toujours en attente',
    'failed_to_check_payment_status': 'Échec de la vérification du paiement',
    'back_to_payment_methods': 'Retour aux moyens de paiement',
    'all_payments_secure': 'Tous les paiements sont sécurisés.',
    'global_coverage': 'Couverture mondiale',
    'multiple_currencies': 'Devises multiples',
    'instant_processing': 'Traitement instantané',
    'local_banking': 'Banques locales',
    'tunisian_dinar': 'Dinar tunisien',
    'trusted_partner': 'Partenaire de confiance',

  },
  ar: {
    // Header
    'cart': 'السلة',
    'login': 'تسجيل الدخول',
    'logout': 'تسجيل الخروج',
    'my_profile': 'ملفي الشخصي',
    'admin_dashboard': 'لوحة الإدارة',
    'loading': 'جاري التحميل...',
    
    // Navigation
    'home': 'الرئيسية',
    'products': 'المنتجات',
    'categories': 'الفئات',
    'about': 'حول',
    'contact': 'اتصل بنا',
    
    // Product related
    'add_to_cart': 'أضف إلى السلة',
    'remove_from_cart': 'إزالة من السلة',
    'price': 'السعر',
    'quantity': 'الكمية',
    'total': 'المجموع',
    'subtotal': 'المجموع الفرعي',
    'tax': 'الضريبة',
    'shipping': 'الشحن',
    'free_shipping': 'شحن مجاني',
    
    // Checkout
    'checkout': 'إتمام الطلب',
    'order_summary': 'ملخص الطلب',
    'payment_method': 'طريقة الدفع',
    'shipping_address': 'عنوان الشحن',
    'billing_address': 'عنوان الفواتير',
    'place_order': 'تقديم الطلب',
    'order_confirmation': 'تأكيد الطلب',
    
    // Invoice
    'invoice': 'فاتورة',
    'bill_to': 'فاتورة إلى',
    'description': 'الوصف',
    'qty': 'الكمية',
    'thank_you': 'شكراً لثقتكم',
    'download_pdf': 'تحميل PDF',
    'close': 'إغلاق',
    
    // Profile
    'profile': 'الملف الشخصي',
    'edit_profile': 'تعديل الملف الشخصي',
    'change_password': 'تغيير كلمة المرور',
    'address': 'العنوان',
    'user_orders': 'الطلبات',
    'settings': 'الإعدادات',
    
    // Auth
    'register': 'تسجيل',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'name': 'الاسم',
    'city': 'المدينة',
    'country': 'البلد',
    'zip_code': 'الرمز البريدي',
    'subscribe': 'الاشتراك في النشرة الإخبارية',
    'forgot_password': 'نسيت كلمة المرور؟',
    'already_have_account': 'لديك حساب بالفعل؟',
    'dont_have_account': 'ليس لديك حساب؟',
    'sign_up': 'تسجيل',
    'sign_in': 'تسجيل الدخول',
    
    // Messages
    'welcome': 'مرحباً',
    'login_success': 'تم تسجيل الدخول بنجاح!',
    'logout_success': 'تم تسجيل الخروج بنجاح',
    'registration_success': 'تم التسجيل بنجاح!',
    'error_occurred': 'حدث خطأ',
    'network_error': 'خطأ في الشبكة، يرجى المحاولة مرة أخرى',
    'opening_password_change': 'فتح تغيير كلمة المرور',
    'changing_password': 'جاري تغيير كلمة المرور',
    'updating_profile': 'جاري تحديث الملف الشخصي...',
    'error_loading_profile': 'خطأ في تحميل الملف الشخصي',
    'edit_mode_enabled': 'تم تفعيل وضع التعديل',
    'password_change_cancelled': 'تم إلغاء تغيير كلمة المرور',
    'cancelling_order': 'جاري إلغاء الطلب...',
    'cancelling': 'جاري الإلغاء...',
    'order_cancelled_successfully': 'تم إلغاء الطلب بنجاح',
    'error_cancelling_order': 'خطأ في إلغاء الطلب',
    'profile_updated_successfully': 'تم تحديث الملف الشخصي بنجاح',
    'error_updating_profile': 'خطأ في تحديث الملف الشخصي',
    'passwords_do_not_match': 'كلمتا المرور غير متطابقتين',
    'password_must_be_at_least_6_characters': 'يجب أن لا تقل كلمة المرور عن 6 أحرف',
    'password_updated_successfully': 'تم تحديث كلمة المرور بنجاح',
    'error_changing_password': 'خطأ في تغيير كلمة المرور',
    'administrator': 'مدير',
    'client': 'عميل',
    'items': 'عناصر',
    'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
    
    // Admin
    'dashboard': 'لوحة التحكم',
    'users': 'المستخدمون',
    'admin_orders': 'الطلبات',
    'admin_products': 'المنتجات',
    'statistics': 'الإحصائيات',
    'notifications': 'الإشعارات',
    
    // Common
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'edit': 'تعديل',
    'delete': 'حذف',
    'view': 'عرض',
    'search': 'بحث',
    'filter': 'تصفية',
    'sort': 'ترتيب',
    'all': 'الكل',
    'yes': 'نعم',
    'no': 'لا',
    'ok': 'موافق',
    'back': 'رجوع',
    'next': 'التالي',
    'previous': 'السابق',
    'submit': 'إرسال',
    'reset': 'إعادة تعيين',
    'clear': 'مسح',
    'error': 'خطأ',
    'success': 'نجح',
    'warning': 'تحذير',
    'info': 'معلومات',
    'role': 'الدور',
    'actions': 'الإجراءات',
    'no_users_found': 'لم يتم العثور على مستخدمين',
    'get_started_add_user': 'ابدأ بإضافة أول مستخدم إلى النظام.',
    'manage_products_inventory': 'إدارة منتجاتك ومخزونك',
    'product_information': 'معلومات المنتج',
    'stock_status': 'حالة المخزون',
    'track_manage_orders': 'تتبع وإدارة طلبات العملاء',
    'order_details': 'تفاصيل الطلب',
    'customer': 'العميل',
    'amount': 'المبلغ',
    'status': 'الحالة',
    'add_new': 'إضافة جديد',
    'user': 'المستخدم',
    'product': 'المنتج',
    'order': 'الطلب',
    'total_users': 'إجمالي المستخدمين',
    'total_products': 'إجمالي المنتجات',
    'total_orders': 'إجمالي الطلبات',
    'total_revenue': 'إجمالي الإيرادات',
    'no_notifications': 'لا توجد إشعارات',
    'address_details': 'تفاصيل العنوان',
    'street_address': 'عنوان الشارع',
    'admin': 'المدير',
    'stock_quantity': 'كمية المخزون',
    'product_name': 'اسم المنتج',
    'category': 'الفئة',
    'subcategory': 'الفئة الفرعية',
    'product_image': 'صورة المنتج',
    'unknown_user': 'مستخدم غير معروف',
    'no_email_provided': 'لم يتم توفير بريد إلكتروني',
    'unknown': 'غير معروف',
    'no_location': 'لا يوجد موقع',
    'view_details': 'عرض التفاصيل',
    'edit_user': 'تعديل المستخدم',
    'delete_user': 'حذف المستخدم',
    'out_of_stock': 'نفذ من المخزون',
    'unavailable_for_purchase': 'غير متوفر للشراء',
    'in_stock': 'متوفر في المخزون',
    'low_stock': 'مخزون منخفض',
    'edit_product': 'تعديل المنتج',
    'delete_product': 'حذف المنتج',
    'no_products_found': 'لم يتم العثور على منتجات',
    'get_started_add_product': 'ابدأ بإضافة أول منتج إلى الكتالوج.',
    'unknown_date': 'تاريخ غير معروف',
    'edit_order': 'تعديل الطلب',
    'delete_order': 'حذف الطلب',
    'no_orders_found': 'لم يتم العثور على طلبات',
    'get_started_add_order': 'ستظهر الطلبات هنا عندما يبدأ العملاء في تقديمها.',
    'payment_successful': 'تم الدفع بنجاح!',
    'payment_success_message': 'تمت معالجة دفعتك بنجاح. شكراً لك على الشراء!',
    'order_confirmed': 'تم تأكيد الطلب',
    'order_confirmation_message': 'تم تأكيد طلبك وسيتم معالجته قريباً. ستتلقى تأكيداً بالبريد الإلكتروني مع تفاصيل الطلب.',
    'return_to_home': 'العودة إلى الرئيسية',
    'view_order_status': 'عرض حالة الطلب',
    'payment_error': 'خطأ في الدفع',
    'payment_error_message': 'حدث خطأ أثناء عملية الدفع. لا تقلق، لم يتم خصم أي رسوم من حسابك.',
    'payment_error_help': 'إذا استمرت في مواجهة مشاكل، يرجى الاتصال بفريق الدعم أو المحاولة مرة أخرى بطريقة دفع مختلفة.',
    'try_again': 'حاول مرة أخرى',
    'payment_pending': 'معالجة الدفع',
    'payment_pending_message': 'دفعك قيد المعالجة. قد يستغرق هذا بضع لحظات. سنخطرك بالبريد الإلكتروني بمجرد تأكيد الدفع.',
    'payment_pending_warning': 'يرجى عدم إغلاق هذه الصفحة أو تحديث المتصفح أثناء معالجة الدفع.',
    'check_order_status': 'فحص حالة الطلب',
    'back_to_home': 'العودة إلى الرئيسية',
    'payment_session_created': 'تم إنشاء جلسة الدفع بنجاح',
    'failed_to_load_payment_session': 'فشل في تحميل جلسة الدفع',
    'failed_to_create_payment_session': 'فشل في إنشاء جلسة الدفع',
    'new_address_added': 'تم إضافة العنوان الجديد بنجاح',
    'using_profile_address': 'استخدام عنوان الملف الشخصي',
    'failed_to_create_guest_user': 'فشل في إنشاء المستخدم الضيف',
    'failed_to_create_order': 'فشل في إنشاء الطلب',
    'order_created_successfully': 'تم إنشاء الطلب بنجاح',
    'shopping_cart': 'سلة التسوق',
    'cart_empty': 'سلة التسوق فارغة.',
    'continue_shopping': 'مواصلة التسوق',
    'clear_cart': 'تفريغ السلة',
    'each': 'كل',
    'remove': 'إزالة',
    'payment_details': 'تفاصيل الدفع',
    'loading_payment_system': 'جاري تحميل نظام الدفع...',
    'payment_failed_try_again': 'فشل الدفع. يرجى المحاولة مرة أخرى.',
    'proceed_to_checkout': 'المتابعة إلى الدفع',
    'special_offers': 'العروض الخاصة',
    'free_shipping_all_orders': 'شحن مجاني على جميع الطلبات',
    'thirty_day_return_policy': 'سياسة الإرجاع لمدة 30 يوماً',
    'secure_checkout_guaranteed': 'دفع آمن مضمون',
    'in_stock_count': 'في المخزون',
    'added_to_cart': 'تمت الإضافة إلى السلة!',
    'active': 'نشط',
    'left': 'الكمية المتبقية',
    'add': 'إضافة',
    'stock_available': 'المخزون متوفر',
    'units': 'وحدات',
    'no_description_available': 'لا توجد وصف لهذا المنتج.',
    'not_specified': 'غير محدد',
    'add_to_cart_quantity': 'إضافة إلى السلة',
    'product_added_to_cart': 'تمت الإضافة إلى السلة!',
    'view_my_cart': 'عرض سلة التسوق',
    'close_modal': 'إغلاق النافذة',
    'profile_information': 'معلومات الملف الشخصي',
    'account_overview': 'نظرة عامة على الحساب',
    'account_type': 'نوع الحساب',
    'ADMIN': 'مدير',
    'security': 'الأمان',
    'manage_your_account_security': 'إدارة أمان حسابك',
    'order_history': 'سجل الطلبات',
    'show_more_orders': 'عرض المزيد من الطلبات',
    'show_less': 'عرض أقل',
    'more': 'أخرى',
    'show_more': 'عرض المزيد',
    'showing': 'عرض',
    'of': 'من',
    'products_count': 'منتجات',
    'try_adjusting_filters': 'حاول تعديل المرشحات',
    'no_address_provided': 'لم يتم توفير عنوان',
    'use_profile_address': 'استخدام عنوان الملف الشخصي',
    'no_address_on_file': 'لا يوجد عنوان مسجل',
    'add_new_address': 'إضافة عنوان جديد',
    'enter_shipping_address': 'إدخال عنوان الشحن',
    'enter_different_shipping_address': 'إدخال عنوان شحن مختلف',
    'please_provide_shipping_address': 'يرجى توفير عنوان الشحن الخاص بك',
    'select_country': 'اختر البلد',
    'continue': 'متابعة',
    'full_name': 'الاسم الكامل',
    'select_your_country': 'اختر بلدك',
    'enter_your': 'أدخل',
    'not_provided': 'غير مقدم',
    'saving': 'جاري الحفظ...',
    'your_orders_will_appear_here': 'ستظهر طلباتك هنا عندما تقوم بعمليات الشراء',
    'passed_on': 'تم الطلب في',
    'login_to_your_account': 'تسجيل الدخول إلى حسابك',
    'create_account_few_steps': 'أنشئ حسابك في بضع خطوات',
    'logging_in': 'جاري تسجيل الدخول...',
    'create_account': 'إنشاء حساب',
    'your_full_name': 'اسمك الكامل',
    'minimum_8_characters': 'الحد الأدنى 8 أحرف',
    'strength': 'القوة',
    'street_address_placeholder': '123 الشارع الرئيسي',
    'your_city': 'مدينتك',
    'subscribe_newsletter': 'أريد تلقي العروض الخاصة والأخبار عبر البريد الإلكتروني',
    'signing_up': 'جاري التسجيل...',
    'currency_converter': 'محول العملات',
    'choose_preferred_currency': 'اختر العملة المفضلة لديك',
    'euro': 'يورو',
    'dinar': 'دينار',
    'exchange_rate': 'سعر الصرف',
    'real_time_rate': 'سعر فوري',
    'my_orders': 'طلباتي',
    'no_orders_yet': 'لم تقم بتقديم أي طلبات بعد.',
    'pending': 'قيد الانتظار',
    'processing': 'قيد المعالجة',
    'shipped': 'تم الشحن',
    'delivered': 'تم التوصيل',
    'cancelled': 'ملغي',
    'confirm_delete_order': 'هل أنت متأكد من حذف هذا الطلب؟',
    'order_deleted_successfully': '✅ تم حذف الطلب بنجاح!',
    'error_deleting_order': 'خطأ في حذف الطلب',
    'unknown_error': 'خطأ غير معروف',
    'no_orders': 'لا توجد طلبات',
    'secure_your_account': 'أمن حسابك',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'updating': 'جاري التحديث...',
    'update': 'تحديث',
    'member_since': 'عضو منذ',
    'street': 'الشارع',
    'view_my_orders': 'عرض طلباتي',
    'order_total': 'طلب',
    'orders_total': 'طلبات',
    'electronics_hub': 'مركز الإلكترونيات',
    'browse_by_category': 'تصفح حسب الفئة',
    'expand_subcategories': 'توسيع الفئات الفرعية',
    'reset_filters': 'إعادة تعيين المرشحات',
    
    // Reviews
    'reviews': 'التقييمات',
    'write_review': 'اكتب تقييماً',
    'rating': 'التقييم',
    'comment': 'التعليق',
    'submit_review': 'إرسال التقييم',
    'submitting': 'جاري الإرسال...',
    'comment_required': 'التعليق مطلوب',
    'rating_required': 'يجب أن يكون التقييم بين 1 و 5',
    'login_to_review': 'يرجى تسجيل الدخول لكتابة تقييم',
    'write_review_placeholder': 'شارك تجربتك مع هذا المنتج...',
    'no_reviews_yet': 'لا توجد تقييمات بعد. كن أول من يقيم هذا المنتج!',
    'error_submitting_review': 'خطأ في إرسال التقييم',
    'error_updating_review': 'خطأ في تحديث التقييم',
    'error_deleting_review': 'خطأ في حذف التقييم',
    'confirm_delete_review': 'هل أنت متأكد من حذف هذا التقييم؟',
    'rating_1': 'سيء',
    'rating_2': 'مقبول',
    'rating_3': 'جيد',
    'rating_4': 'جيد جداً',
    'rating_5': 'ممتاز',
    // Payment Method Selector
    'choose_payment_method': 'اختر طريقة الدفع',
    'select_payment_method_description': 'اختر طريقة الدفع المفضلة لديك للمتابعة في عملية دفع آمنة',
    'adyen_description': 'ادفع بأمان باستخدام البطاقات والمحافظ الدولية.',
    'paymee_description': 'ادفع بطرق محلية وبنوك تونسية.',
    // Paymee Payment
    'paymee_payment': 'دفع بايمي',
    'secure_payment_with_paymee': 'دفع آمن مع بايمي',
    'waiting_for_payment': 'في انتظار دفع بايمي',
    'please_complete_payment_in_new_tab': 'يرجى إكمال الدفع في علامة التبويب الجديدة.',
    'polling_attempts': 'محاولات التحقق',
    'retry_check_payment_status': 'إعادة محاولة التحقق من الدفع',
    
    'redirecting_to_paymee': 'سيتم توجيهك إلى بايمي لإكمال الدفع.',
    'proceed_to_paymee': 'الانتقال إلى بايمي',
    'payment_instructions': 'تعليمات الدفع',
    'click_proceed_to_complete_payment': "انقر على 'الانتقال إلى بايمي' لإكمال الدفع.",
    'payment_page_will_open_new_tab': 'ستفتح صفحة الدفع في علامة تبويب جديدة.',
    'return_here_after_payment': 'عد هنا بعد الدفع للتحقق من حالتك.',

    'creating_payment': 'جاري إنشاء الدفع',
    'pay_with_paymee': 'ادفع مع بايمي',
    'secure_payment': 'دفع آمن',
    'paymee_secure_encryption': 'بايمي يستخدم تشفيرًا آمنًا',
    'no_card_details_stored': 'لا يتم تخزين بيانات البطاقة', 
    'instant_payment_confirmation': 'تأكيد الدفع الفوري',
    'payment_created_successfully': 'تم إنشاء الدفع بنجاح',
    'failed_to_create_payment': 'فشل في إنشاء الدفع',
    'payment_still_pending': 'الدفع لا يزال معلقًا',
    'failed_to_check_payment_status': 'فشل في التحقق من حالة الدفع',
    'back_to_payment_methods': 'العودة إلى طرق الدفع',
    'all_payments_secure': 'جميع المدفوعات آمنة.',
    'global_coverage': 'تغطية عالمية',
    'multiple_currencies': 'عملات متعددة',
    'instant_processing': 'معالجة فورية',
    'local_banking': 'بنوك محلية',
    'tunisian_dinar': 'الدينار التونسي',
    'trusted_partner': 'شريك موثوق',
    // Admin Payment Tab


    'select_active_payment_method': 'اختر طريقة الدفع النشطة',
    'payment_method_only_for_clients': 'سيتم عرض هذه الطريقة فقط كطريقة دفع عند التسوق.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('fr');

  useEffect(() => {
    // Load saved language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'fr', 'ar'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    
    // Update document direction for RTL languages
    if (lang === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = lang;
    }
  };

  const t = (key: string): string => {
    const currentTranslations = translations[language] as Record<string, string>;
    return currentTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 